language: c
sudo: required
service: docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
  - cp  mocks/mock.ml lib/nvml.ml
  - cp  mocks/mock.c  stubs/nvml_stubs.c
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=gpumon
    - PINS="gpumon:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
    - BASE_REMOTE_BRANCH="feature/REQ-720/master"
  matrix:
    - DISTRO="debian-9-ocaml-4.07"
